### ISSUE TITLE
sdk example transferWithRelayHandoff() error on transfer SOL->BSC

### ISSUE THREAD

**Issue by placzkowski** [wormhole-foundation/wormhole#1246]
I get error when try to run transferWithRelayHandoff() example on mainnet.  
I managed to use bridgeWsolToEthereum function to send SOL to BSC (changed CHAIN_ID_ETH to CHAIN_ID_BSC). 
When I try to use transferWithRelayHandoff(), I set FCqfQSujuPxy6V42UvafBhsysWtEq1vhjfMN1PUbgaxA (usdcbs) as SOLANA_TEST_TOKEN and decimals to 8. 

Here is log:
'Program 11111111111111111111111111111111 invoke [1]',
    'Program 11111111111111111111111111111111 success',
    'Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA invoke [1]',
    'Program log: Instruction: Approve',
    'Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA consumed 2025 of 1400000 compute units',
    'Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA success',
    'Program wormDTUJ6AWPNvk59vGQbDvGJmqbDTdgWgAqcLBCgUb invoke [1]',
    'Program log: Error: Custom(7)',
    'Program wormDTUJ6AWPNvk59vGQbDvGJmqbDTdgWgAqcLBCgUb consumed 49640 of 1397975 compute units',
    'Program wormDTUJ6AWPNvk59vGQbDvGJmqbDTdgWgAqcLBCgUb failed: custom program error: 0x0'

**Comment by evan-gray** [comment]
That error is due to calling the incorrect Solana method - the token is not native, so the `transfer_wrapped` instruction should be used. The SDK method `transferFromSolana` should handle this automatically. 

Here’s the error mapping https://github.com/wormhole-foundation/wormhole/blob/dev.v2/solana/modules/token_bridge/program/src/lib.rs#L86
