### ISSUE TITLE
sui: Use CoinMetadata to complete token attestation

### ISSUE THREAD

**Issue by kcsongor** [wormhole-foundation/wormhole#1989]
https://github.com/MystenLabs/sui/pull/5635 is merged in, we can now store & read token metadata on-chain

**Comment by optke3** [comment]
CoinMetadata is available on the devnet branch now, so starting this.

https://github.com/MystenLabs/sui/blob/devnet/crates/sui-framework/sources/coin.move

**Comment by optke3** [comment]
I think it’s fair to assume that CoinMetadata is shared, if it is we can for sure get either a mutable or immutable reference to it. Correct me if I’m wrong, but if it is not shared, we can still get a read-only reference to it if we know the object ID?
For register_native_asset, we would have to take in CoinMetadata<CoinType> as an arg. This is guaranteed to correspond to CoinType (the type parameters will match, and the Metadata object is unique, since create_currency<CoinType> can only be called once on a CoinType).

Agree that for Wormhole-created wrapped assets, we should store the CoinMetadata in token bridge, and allow user to retrieve the metadata. Or could simply share it.

**Comment by kcsongor** [comment]
it's not possible to supply an owned object even as a read-only reference (https://docs.sui.io/learn/objects#owned-by-an-address)

the `_cap: &SomeCap` pattern is used in some places to implement access control.

Perhaps we could share the CoinMetadata object, since the functions that modify it also require a TreasuryCap so technically it's safe to share the metadata. It is kind of nice though that the metadata object lives next to the treasury in WrappedAssetInfo, owned by the bridge.

**Comment by optke3** [comment]
I wonder if the Move compiler knows that `CoinMetadata` is mutable, unlike `TreasuryCap`. When I am trying to share the metadata, I'm getting an error from `transfer::share_object`. Do you figure that sharing mutable objects is not supported yet? It says as much in the comments: https://github.com/MystenLabs/sui/blob/devnet/crates/sui-framework/sources/transfer.move#L25

**Comment by kcsongor** [comment]
> I wonder if the Move compiler knows that `CoinMetadata` is mutable, unlike `TreasuryCap`. When I am trying to share the metadata, I'm getting an error from `transfer::share_object`. Do you figure that sharing mutable objects is not supported yet? It says as much in the comments: https://github.com/MystenLabs/sui/blob/devnet/crates/sui-framework/sources/transfer.move#L25


Hm, looks like it's not supported yet. I think we should just put the object into the WrappedAssetInfo for now instead of sharing it.

**Comment by optke3** [comment]
We want to pass `CoinMetadata` to `register_native_asset` as an argument, so it can retrieve the info. However, it seems like can't as 1) there are no exposed getters, 2) it's not a shared object. We should ask Mysten to expose getter funcs for name, symbol, decimals, otherwise this metadata object seems useless.

Is it true that for a shared object struct foo {a: A, b: B}, you can access the fields using foo.a, foo.b even if there is no exposed public getter?

**Comment by kcsongor** [comment]
I don't think you can access anything unless there are exposed getter functions. Object ownership is orthogonal to field access

**Comment by optke3** [comment]
Update: it seems like other people are also having trouble accessing the `CoinMetadata` on-chain: https://github.com/MystenLabs/sui/pull/5635, since there are still no getters for the fields.

It might be worth prodding them again to add getters or putting up a PR ourselves.

**Comment by optke3** [comment]
Relevant branch: https://github.com/wormhole-foundation/wormhole/tree/sui/token_bridge_attestation 

Not ready to be merged yet, because based on main and not devnet of sui

**Comment by optke3** [comment]
PR (ready to be merged into sui/integration): https://github.com/wormhole-foundation/wormhole/pull/2204
