### ISSUE TITLE
Support tokenbridge registration directly in the accounting contract

### ISSUE THREAD

**Issue by jynnantonix** [wormhole-foundation/wormhole#2103]
Currently accounting depends on the tokenbridge contract to check the registered emitter for a particular chain.  Unfortunately, deploying the tokenbridge on wormchain requires some additional work to have it call out to the native wormhole module rather than the core bridge contract.

To break this dependency, we want to deploy an initial version of accounting that uses the known tokenbridge emitters from the sdk along with a mechanism to register a new chain / update an existing registration.  Once the tokenbridge has been deployed on wormchain we can remove the chain registration method and add back the dependency on the tokenbridge.

**Comment by evan-gray** [comment]
Would it be more straightforward to simply replay all the token bridge registrations on the accounting contract after initialization, instead of hard-coding, since that functionality would be required to add emitters after the initial deployment anyway? All those VAAs are handy as they're submitted every time a new token bridge is deployed to a new chain.

**Comment by jynnantonix** [comment]
I was thinking that we could do both: check if there is an emitter address registered or fall back to the one in the sdk.  However if we have all the chain registration VAAs already on hand then I agree there's no reason to use anything from the sdk.
