### ISSUE TITLE
Revise liveness properties in token bridge (& NFT bridge) whitepaper

### ISSUE THREAD

**Issue by kcsongor** [wormhole-foundation/wormhole#2208]
The following two documents
https://github.com/wormhole-foundation/wormhole/blob/main/whitepapers/0003_token_bridge.md#caveats
https://github.com/wormhole-foundation/wormhole/blob/main/whitepapers/0006_nft_bridge.md#caveats
claim that transactions can get stuck indefinitely due to guardian set changes. While this statement is true in general, there do exist recovery mechanisms for many common scenarios, so we should consider updating the documents to include those.
Some of these, off the top of my head:
1. The subset of guardians that persist between guardian set changes is still enough to reach quorum, and they can simply reobserve the transaction.
2. The new guardians replayed all transactions from genesis (or at least from some state that's older than the missing transaction) and they can reobserve the message.
3. With https://github.com/wormhole-foundation/wormhole/pull/2183 a new guardian can sign a VAA even if it hasn't seen it, by trusting an earlier guardian set (and if at most one signature is missing to reach quorum again).

**Comment by SEJeff** [comment]
> The subset of guardians that persist between guardian set changes is still enough to reach quorum, and they can simply reobserve the transaction.

If the subset of guardians that persist enough between guardian set changes is still enough to reach quorum, a reobservation is not needed. The vaa can be manually edited to increment the gst and update some metadata after removing the removed guardian signature/s. Then the vaa can be manually redeemed. This does not require re-observation. @ckeun did magic for this but I believe it is now in the sdk or cli tooling.

> The new guardians replayed all transactions from genesis (or at least from some state that's older than the missing transaction) and they can reobserve the message.
This is simply running an archive node for a given chain. For some chains everyone to run archive nodes and for most we don't. However, there is precedent for the guardians to upgrade to archive nodes when the majority missed a hard fork (terra classic IIRC) so that some missed tx could be reobserved.

**Comment by kcsongor** [comment]
> If the subset of guardians that persist enough between guardian set changes is still enough to reach quorum, a reobservation is not needed. The vaa can be manually edited to increment the gst and update some metadata after removing the removed guardian signature/s.

This is only the case if a quorum number of persisting guardians have signed the VAA, which often is not the case. Anyway, that scenario is a special case of 1. so I'm not sure it's necessary to discuss it separately.

> This is simply running an archive node for a given chain. The tx/s that were missed will be on the local rpc disk.

Sure, but a new guardian that just joined recently, will they have an archive node with all the old txs available?
