### ISSUE TITLE
Global accountant: Message signature format doesn’t follow guidelines for guardian key usage

### ISSUE THREAD

**Issue by aadam-10** [wormhole-foundation/wormhole#2294]
### Discussed in https://github.com/wormhole-foundation/wormhole/discussions/2292

<div type='discussions-op-text'>

<sup>Originally posted by **tbjump** December 15, 2022</sup>
## Status Quo

The Guardian key is being used to sign a JSON message about an observation to be submitted to the Accounting contract. 

## Issue

The signature format doesn’t follow the recommendation of [the whitepaper](https://github.com/wormhole-foundation/wormhole/blob/main/whitepapers/0009_guardian_key.md), which is to prepend a message type identifier of `>=34` bytes. 

## Recommendation

In this line of code: 

[[wormhole/accounting.go at 7f512425dcf5425957c6921ed130caa9569023ab · wormhole-foundation/wormhole](https://github.com/wormhole-foundation/wormhole/blob/7f512425dcf5425957c6921ed130caa9569023ab/node/pkg/accounting/accounting.go#L330)](https://github.com/wormhole-foundation/wormhole/blob/7f512425dcf5425957c6921ed130caa9569023ab/node/pkg/accounting/accounting.go#L330)

I propose that instead of computing `digest := Keccak256Hash(Keccak256Hash(observation))`, compute `digest := Keccak256Hash(ACCOUNTING_OBSERVATION_PREFIX + observation)` , where `ACCOUNTING_OBSERVATION_PREFIX = ACCOUNTING_OBSERVATION_00000000000`

The corresponding changes also need to be made in the Accounting contract. 

Finally, this additional guardian key usage should be documented in the Whitepaper [https://github.com/wormhole-foundation/wormhole/blob/main/whitepapers/0009_guardian_key.md](https://github.com/wormhole-foundation/wormhole/blob/main/whitepapers/0009_guardian_key.md)</div>

**Comment by evan-gray** [comment]
All changes should conform to https://github.com/wormhole-foundation/wormhole/blob/main/whitepapers/0009_guardian_key.md to prevent leaking a signature which could be maliciously applied to a future change (were it to also not conform to the recommendation).

**Comment by evan-gray** [comment]
Update, the line of code is now at https://github.com/wormhole-foundation/wormhole/blob/main/node/pkg/accountant/submit_obs.go#L332

**Comment by tbjump** [comment]
Actually, this issue is not fully addressed yet. The payload prefix was added

1. the signing of accounting messages is still using double-Keccak256 as opposed to a single Keccak256 as required in https://github.com/wormhole-foundation/wormhole/blob/main/whitepapers/0009_guardian_key.md. https://github.com/wormhole-foundation/wormhole/blob/718cd3b1b3775640d81e81098f4cd6ab7d856bf3/node/pkg/accountant/submit_obs.go#L334
2. Please add this usage of the guardian key to the whitepaper https://github.com/wormhole-foundation/wormhole/blob/main/whitepapers/0009_guardian_key.md
