### ISSUE TITLE
wrapped BNB not wrapped BNB on BSC

### ISSUE THREAD

**Issue by 0xksure** [wormhole-foundation/wormhole#3118]
## Steps to reproduce

I'm calling 
```ts
const tokenBridgeAddress = 0xB6F6D86a8f9879A9c87f643768d9efc38c1Da6E7
const address = 0xbb4CdB9CBd36B01bD1cBaEBF2De08d9173bc095c
const wormholeChainId = 4
const originalAsset = getOriginalAssetEth(
    tokenBridgeAddress,
    provider,
    token.address,
    wormholeChainId
  )
```
and it turns out that `originalAsset.isWrapped` is false. However, according to
- https://bscscan.com/address/0xbb4CdB9CBd36B01bD1cBaEBF2De08d9173bc095c
- https://github.com/wormhole-foundation/wormhole-token-list/blob/main/content/by_source.csv
It seems as if `isWrapped` should be true. 

## Expected behavior

I expect that  `0xbb4CdB9CBd36B01bD1cBaEBF2De08d9173bc095c` is the wrapped version of BNB on BSC.

**Comment by aadam-10** [comment]
hi @0xksure, the property refers to it being a wormhole wrapped token, which in this case is false, because this token has not been wrapped by wormhole.

**Comment by 0xksure** [comment]
> hi @0xksure, the property refers to it being a wormhole wrapped token, which in this case is false, because this token has not been wrapped by wormhole.

Ok that makes sense, thanks for the answer. So tokens in the wormhole token list are just tokens supported by the token bridge but not necessarily wrapped by wormhole? Also, is the token bridge authorized to unwrap the wrapped bnb in question on bsc?

**Comment by aadam-10** [comment]
The token list is for convenience to quicky find and reference popular tokens and their wormhole contracts on a particular chain. Wormhole permissionlessly supports any token but not all end up on this list. In the by_source.csv file that you'd linked, `0xbb4CdB9CBd36B01bD1cBaEBF2De08d9173bc095c` is found in the origin column, so that's the token which Wormhole considers the 'unwrapped' variant.

When transferring this token back to bnb, the token can be unwrapped when redeeming by calling `completeTransferAndUnwrapETH`. If you already have the wrapped bnb on BSC, then you can unwrap it by calling `withdraw` on withdraw https://bscscan.com/token/0xbb4CdB9CBd36B01bD1cBaEBF2De08d9173bc095c#writeContract without involvement from Wormhole.

**Comment by 0xksure** [comment]
> The token list is for convenience to quicky find and reference popular tokens and their wormhole contracts on a particular chain. Wormhole permissionlessly supports any token but not all end up on this list. In the by_source.csv file that you'd linked, `0xbb4CdB9CBd36B01bD1cBaEBF2De08d9173bc095c` is found in the origin column, so that's the token which Wormhole considers the 'unwrapped' variant.
> 
> When transferring this token back to bnb, the token can be unwrapped when redeeming by calling `completeTransferAndUnwrapETH`. If you already have the wrapped bnb on BSC, then you can unwrap it by calling `withdraw` on https://bscscan.com/token/0xbb4CdB9CBd36B01bD1cBaEBF2De08d9173bc095c#writeContract without involvement from Wormhole.

So if I understand you correctly, `0xbb4CdB9CBd36B01bD1cBaEBF2De08d9173bc095c` is a wrapped bnb on BSC which can be unwrapped and transferred to another chain using wormhole portal. However, since it's not wormhole that wrapped the token `isWrapped` is false. Is that correct?

**Comment by aadam-10** [comment]
100% correct.
