### ISSUE TITLE
Client/js: Fake Worm CLI commands on README documentation

### ISSUE THREAD

**Issue by AlberErre** [wormhole-foundation/wormhole#3152]
## Description and context

Currently, there are many non-existent (fake) Worm CLI commands present on the README documentation.

This issue was detected while reviewing PR #2631, here: https://github.com/wormhole-foundation/wormhole/pull/2631#issuecomment-1612868768

e.g.

Command `worm verify-vaa init-token-bridge` does not exist as a valid command on the current Worm CLI. However, it is present on the `clients/js/README` file.

## Steps to reproduce

1. Build worm CLI tool locally using `make install` on `clients/js` folder.
2. Visit `clients/js/README` file
3. Try some fake commands from README file on `worm` CLI

## Experienced behavior

There are several commands described on README file that does not exist on the current `worm` CLI implementation. 

e.g. 
`worm verify-vaa init-token-bridge`

## Expected behavior

Every commands present on README documentation should exist and work properly.

## Solution recommendation

Debug and fix `clients/js/src/doc.ts`, which is the source file that triggers `make docs` command. This source code is generating the incorrect README documentation.

**Comment by AlberErre** [comment]
@aadam-10 just reported this issue detected while reviewing the Worm CLI tests 👀

**Comment by kcsongor** [comment]
Looks like the issue is that https://github.com/wormhole-foundation/wormhole/blob/aa03d417193814c6a82f28dee83bf2e715941dd4/clients/js/src/doc.ts#L22-L24
mutates the same underlying `yargs` instance, and subcommands are not differentiated in their respective builders, e.g.

https://github.com/wormhole-foundation/wormhole/blob/aa03d417193814c6a82f28dee83bf2e715941dd4/clients/js/src/cmds/verifyVaa.ts#L12-L20.

To fix it, during doc generation we could attempt to create a fresh clone of `yargs` for each invocation.
