### ISSUE TITLE
BUG: Urgent Request for Fixing Terra Bridge Issue on Wormhole

### ISSUE THREAD

**Issue by KylerLizi** [wormhole-foundation/wormhole#3633]
Dear Wormhole Team,

I hope this message finds you well. I am writing to you as an ardent user of the Wormhole network, specifically concerning the Terra bridge functionality that has been out of service for several months. The inability to use this bridge has caused significant inconvenience and distress, as my funds have been immovably stuck within the system for an extended period.

In November, there were discussions on Discord indicating that a fix might be available by December. Additionally, I've observed corresponding code submissions on GitHub, which raised my hopes for a resolution. However, it has been over a month since these developments, and I am still unable to use the bridge on the frontend.

The prolonged unavailability of this service is more than just an inconvenience; it has tangible impacts on my financial situation. I understand that resolving such issues can be complex and time-consuming, but I implore the Wormhole team to prioritize this matter. The community's trust and your platform's credibility are at stake.

I kindly request a clear update on the situation. If the fix is imminent, please provide a definitive timeline. If there are unexpected delays or complications, being transparent about these challenges would be greatly appreciated. Your prompt and decisive action on this matter is crucial.

I remain hopeful and confident in your team's ability to resolve this issue. Your commitment to service excellence and user satisfaction has always set Wormhole apart. Please consider this request with the urgency it entails, as many of us rely on your services for our blockchain endeavors.

Thank you for your attention to this matter. I look forward to a positive resolution and continued use of Wormhole's services.

Best regards.

**Comment by claudijd** [comment]
Hi everyone,

There has recently been a challenge for Terra Classic users not being able to transfer Wormhole-wrapped assets back into Terra Classic. This is due to the Terra Classic chain performing a breaking change by updating an internal dependency which requires modifications to the Terra Classic Wormhole smart contract.

We expect users should be able to transfer assets to Terra Classic on or before January 26, 2024. Upgrades to Wormhole's Terra Classic contracts have already been internally audited by Wormhole Security Contributors and are currently being audited by an external security firm.

We appreciate everyone’s patience while we prioritize these audits for the safety of the Wormhole protocol, and we will communicate an update in this channel as soon as this functionality is live for Terra Classic users.

Thank you.

**Comment by tonyjin** [comment]
From the Wormhole Discord:
> Transfers of Wormhole-wrapped assets back into Terra Classic have been re-enabled. You can use Portal (https://portalbridge.com/advanced-tools/) or another UI to resume these transfers.
> 
> We appreciate everyone’s patience as we prioritized and implemented the right solution for the safety of the Wormhole community.
